### PR TITLE
fix(helm): improve documentation and grafana dashboard

### PR DESCRIPTION
**Pull request by genofire**
### Pull Request Checklist

* [x] I have added Go unit tests or [Complement integration tests](https://github.com/matrix-org/complement) for this PR _or_ I have justified why this PR doesn't need tests
* [x] Pull request includes a [sign off below using a legally identifiable name](https://matrix-org.github.io/dendrite/development/contributing#sign-off) _or_ I have already signed off privately

---

* **docs**: enabling of metrics in there config is needed
* **dashboard**: since the imported dashboard was created:
  * many metrics was dropped by dendrite (mainly #2967)
  * grafana has new version of diagrams ...

### CODE REVIEW

**Comment by genofire** [comment]
only possible metrics:

```openmetrics
# HELP dendrite_caching_ristretto_cost 
# HELP dendrite_caching_ristretto_ratio 
# HELP dendrite_clientapi_reg_users_total Total number of registered users
# HELP dendrite_federationapi_destination_queues_backing_off 
# HELP dendrite_federationapi_destination_queues_running 
# HELP dendrite_federationapi_destination_queues_total 
# HELP dendrite_federationapi_recv_edus Number of incoming EDUs from remote servers
# HELP dendrite_syncapi_active_sync_requests The number of sync requests that are active right now
# HELP dendrite_syncapi_waiting_sync_requests The number of sync requests that are waiting to be woken by a notifier
```

**Comment by S7evinK** [comment]
Why are only those possible?

**Comment by genofire** [comment]
Dont ASK me, i believe the other was removed.

**Comment by genofire** [comment]
yes you are correct, after few incomming request that metrics are all visible ...

**Comment by genofire** [comment]
removed diagrams need metric:
  - dendrite_caching_in_memory_lru_roomserver_room_ids
  - dendrite_caching_in_memory_lru_federation_event
  - dendrite_caching_in_memory_lru_server_key
  - dendrite_roomserver_processroomevent_duration_millis_bucket
  - dendrite_clientapi_sendevent_duration_millis_bucket (Sendevent Duration)
  - process_cpu_seconds_total (CPU usage)

**Review by S7evinK — APPROVED** [review]

**Pull request merged**
