### PR TITLE
Move makeUserID into userutil and prevent code duplication

### PR DESCRIPTION
**Pull request by APwhitehat**
It's raining in my city but I love DRY.

### CODE REVIEW

**Comment by anoadragon453** [comment]
To be fair, this is probably something else that should go in gomatrixserverlib, but so should the rest of userutil IMO.

Will merge this for now for code cleanup. Then we should at some point take a good hard look at the utility stuff in Dendrite and see what should be extracted into the general server lib.

**Comment by APwhitehat** [comment]
I feel the same way. 

Many stuff could be moved to gomatrixserverlib.
Should definitely try to do that in near future.

**Comment by APwhitehat** [comment]
ah, ungraceful merge. I'll fix this.

**Comment by anoadragon453** [comment]
Looks good. Thanks!

**Pull request merged**
