### PR TITLE
use jsoniter instead of encoding/json

### PR DESCRIPTION
**Pull request by bn4t**
### Pull Request Checklist

* [x] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

Uses jsoniter instead of encoding/json wherever possible. With some structs from gomatrixserverlib it's currently not possible to use jsoniter.

Some sytest tests seem to fail with this change. I suspect this is because jsoniter sorts map keys differently than encoding/json.
If this is the case jsoniter could be configured to sort map keys like encoding/json.

Signed-off-by: `Benjamin Nater <me@bn4t.me>`

### CODE REVIEW

**Review by neilalexander — COMMENTED** [review]
It might be easier to use named imports here, e.g. `import json "github.com/json-iterator/go`, that way we don't need to change every place we deal with JSON.

**Comment by bn4t** [comment]
@neilalexander Okay, will change that.

**Comment by bn4t** [comment]
So, it seems like the reason sytest tests failed was because gomatrixserverlib still used encoding/json. With a modified version of gomatrixserverlib that uses jsoniter the failures no longer seem to happen.

However now the `TestUpdateNoPrevID` unit test fails. Might be because jsoniter sorts map keys differently.

**Comment by bn4t** [comment]
Okay, this is odd. For some reason the `TestUpdateNoPrevID` unit test works on my machine.

**Comment by bn4t** [comment]
Sytest still fails despite using `ConfigCompatibleWithStandardLibrary`. Any idea why this could be @neilalexander ? I'm kinda stuck here.

**Comment by bn4t** [comment]
Closing this because of lack of time from my side.

**Pull request closed without merging**
