### PR TITLE
Only include go-sqlite3 on the relevant binaries

### PR DESCRIPTION
**Pull request by neilalexander**
This should stop us from pulling `go-sqlite3` whatsoever on the WASM builds, which use `go-sqlite3-js` instead.

cc @jryans

### CODE REVIEW

**Comment by kegsay** [comment]
We shouldn't need this. This is done in `internal/sqlutil`:
 - https://github.com/matrix-org/dendrite/blob/b21089e75d0602ba4f74716a283b94897b21d745/internal/sqlutil/trace_driver_wasm.go#L22
 - https://github.com/matrix-org/dendrite/blob/b21089e75d0602ba4f74716a283b94897b21d745/internal/sqlutil/trace_driver.go#L23

What's the actual problem here? Does it not build or something?

**Comment by kegsay** [comment]
Oh right, I think I see. You're omitting `mattn/sqlite3` entirely in WASM builds? Why though? We switch on this at https://github.com/matrix-org/dendrite/blob/master/internal/sqlutil/sql.go#L116:L121

**Comment by jryans** [comment]
This does indeed get past the SQLite driver registration error, but now there seems to be a new issue:
```
Open -> /idb/dendritejs_account.db err= <nil> 2073:59:19
time="2021-07-06T10:15:58.773000000Z" level=panic msg="failed to connect to accounts db" func="CreateAccountsDB\n\t" file=" [/Users/jryans/Projects/Matrix/dendrite/setup/base.go:285]" error="RunDeltas: Failed to EnsureDBVersion: no next version found" 2073:59:19
panic: (*logrus.Entry) 0x1244000 2073:59:19
<empty string> 2073:59:19
goroutine 1 [running]: 2073:59:19
github.com/sirupsen/logrus.(*Entry).log(0x116ff80, 0x0, 0x10cda00, 0x20) 2073:59:19
	/Users/jryans/Projects/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:259 +0x57 2073:59:19
github.com/sirupsen/logrus.(*Entry).Log(0x116ff80, 0x0, 0x10c5c88, 0x1, 0x1) 2073:59:19
	/Users/jryans/Projects/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:285 +0x11 2073:59:19
github.com/sirupsen/logrus.(*Entry).Logf(0x116ff80, 0x0, 0x2b5f7f, 0x20, 0x0, 0x0, 0x0) 2073:59:19
	/Users/jryans/Projects/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:330 +0x12 2073:59:19
github.com/sirupsen/logrus.(*Entry).Panicf(...) 2073:59:19
	/Users/jryans/Projects/go/pkg/mod/github.com/sirupsen/logrus@v1.8.0/entry.go:368 2073:59:19
github.com/matrix-org/dendrite/setup.(*BaseDendrite).CreateAccountsDB(0x10e1680, 0x29d49b, 0x8) 2073:59:19
	/Users/jryans/Projects/Matrix/dendrite/setup/base.go:285 +0x11 2073:59:19
main.main() 2073:59:19
	/Users/jryans/Projects/Matrix/dendrite/cmd/dendritejs-pinecone/main.go:178 +0x40 2073:59:19
exit code: 2
```

**Comment by jryans** [comment]
> What's the actual problem here? Does it not build or something?

The Wasm build would fail to startup with the following:

```
dendrite-sw.js: v0.2.0 starting dendrite.wasm... 1869:149:11
panic: sql: Register called twice for driver sqlite3 2066:59:19
<empty string> 2066:59:19
goroutine 1 [running]: 2066:59:19
database/sql.Register(0x29c713, 0x7, 0x3dd4a8, 0x10505a0) 2066:59:19
	/usr/local/Cellar/go/1.16.5/libexec/src/database/sql/sql.go:51 +0x11 2066:59:19
github.com/mattn/go-sqlite3.init.0() 2066:59:19
	/Users/jryans/Projects/go/pkg/mod/github.com/mattn/go-sqlite3@v1.14.7-0.20210414154423-1157a4212dcb/static_mock.go:19 +0x3 2066:59:19
exit code: 2
```

It seems that importing `mattn/go-sqlite3` anywhere will bring `static_mock` (at least when built for Wasm without `cgo`), which registers the `sqlite3` driver. Some other path then also registers `sqlite3` as well, leading to error above.

**Pull request merged**
