### PR TITLE
Fix SIGSEGV in IsInterestedInRoomID

### PR DESCRIPTION
**Pull request by bodqhrohro**
### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

Signed-off-by: `Bohdan Horbeshko <bodqhrohro@gmail.com>`

### CODE REVIEW

**Comment by bodqhrohro** [comment]
Uh oh, it seems to be a partial duplicate of #1836.
@diamondburned, how about merging our approaches? Your one has a more verbose error handling, while mine is more general and less cohesive.

**Comment by diamondburned** [comment]
Do you prefer you merging my branch into yours so that I can close my PR?

**Comment by bodqhrohro** [comment]
Feel free to close it now if I merged it properly :)
I'm not sure if a commit can have two Signed-Off-By entries, should it?

**Comment by diamondburned** [comment]
That's probably fine.

**Review by Kegsay — APPROVED** [review]

**Comment by Kegsay** [comment]
Thanks for this!

**Pull request merged**
