### PR TITLE
feat: remove config option from server

### PR DESCRIPTION
**Pull request by meenal06**
Signed-off-by: Meenal Trivedi <meenaltrivedi6102@gmail.com>

### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

fixes https://github.com/matrix-org/dendrite/issues/1756

### CODE REVIEW

**Comment by meenal06** [comment]
@kegsay the config file is committed, I started the demo-yggdrasil & it generated that file. Should it be added to gitignore 🤔 ?

**Review by kegsay — CHANGES_REQUESTED** [review]
This isn't the right approach. https://github.com/matrix-org/dendrite/issues/1756 refers only to `dendrite-demo-yggdrasil` - we only want to remove the config option from that binary.

`ParseFlags` must not be touched, as it is used in places where we actually do want to read the config:
```
cmd/dendrite-monolith-server/main.go:47:	cfg := setup.ParseFlags(true)
cmd/dendrite-polylith-multi/main.go:31:	cfg := setup.ParseFlags(true)
cmd/create-account/main.go:69:	cfg := setup.ParseFlags(true)
cmd/resolve-state/main.go:29:	cfg := setup.ParseFlags(true)
```

**Comment by neilalexander** [comment]
I'm not sure I understand what problem this PR is trying to solve?

**Comment by meenal06** [comment]
What would be ideal way to remove Config flag from demo-yggdrassil @kegsay @neilalexander ?

**Comment by kegsay** [comment]
Stale.

**Pull request closed without merging**
