### PR TITLE
Add missing servers field in /directory/room/:alias response

### LINKED ISSUE #659: Tell servers and clients which servers know about an alias
Implement the `server` attribute in [`GET /_matrix/client/r0/directory/room/{roomAlias}`](https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-directory-room-roomalias) responses.

This can be done by setting its value to a list of the servers that are in the room at the time of the request.
As a bonus point, if we needed to use federation to perform the lookup request, we can check and make sure the list contains the server we talked to.

--

Edit: added link to spec ~ @anoadragon453

### PR DESCRIPTION
**Pull request by Cnly**
Fixes #659.

Signed-off-by: Alex Chen <minecnly@gmail.com>

### Pull Request Checklist

* [x] I have added any new tests that need to pass to `testfile` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by anoadragon453** [comment]
So looking at Synapse's code, it:

Checks that the room is owned by itself:

https://github.com/matrix-org/synapse/blob/4806651744616bf48abf408034ab9560e33f60ce/synapse/handlers/directory.py#L235-L280

Then if it is, pulls the list of servers it knows are in a room from the DB and returns that:

https://github.com/matrix-org/synapse/blob/4806651744616bf48abf408034ab9560e33f60ce/synapse/storage/directory.py#L30-L63

I'm not quite sure why, if I'm not the server in the room_id, that I can't answer this query, and presumably this will break if the homeserver that originally created the room leaves it...

**Comment by Cnly** [comment]
Depends on #781.

**Comment by anoadragon453** [comment]
Can we add our own server to the `servers` slice?

**Comment by Cnly** [comment]
> I'm not quite sure why, if I'm not the server in the room_id, that I can't answer this query, and presumably this will break if the homeserver that originally created the room leaves it...

I'm afraid that'll also be Dendrite's behaviour because we don't (?) keep track of remote aliases...

Here Dendrite will first directly check if the alias association is local. If not, it sends a federation query to the domain in the ID. So if the server in the ID is down, this will break.

> Can we add our own server to the `servers` slice?

If the alias is local and we're in that room (which should be impled), then we'll be in the list. If it's resolved via federation, then we'll just use whatever the remote server gives us.

**Comment by anoadragon453** [comment]
So this will fail if the server that the alias is assigned to is down, but that's expected by definition of an alias. That's why you want to create a myriad of aliases for a room across a number of servers to keep it resilient.

So actually I think this is ok! Could you merge this branch forward please? :)

**Pull request merged**
