### PR TITLE
Pushrule tweaks, make `pattern` non-optional on `EventMatchCondition`

### PR DESCRIPTION
**Pull request by S7evinK**
This should fix https://github.com/matrix-org/dendrite/issues/2882 (Tested with FluffyChat 1.7.1)
Also adds tests that the predefined push rules (as per the spec) is what we have in Dendrite.

### CODE REVIEW

**Comment by Undef-a** [comment]
Just tested this one (pulled your branch and built/installed) against Fluffychat 1.7.2 (arm64 flatpak). I still get the old error `Error during processing events - PushCondition is missing pattern`.

**Comment by S7evinK** [comment]
@Undef-a: In case it's possible, can you provide your pushrules (`SELECT * FROM userapi_account_datas WHERE localpart = 'YourLocalpart' and type = 'm.push_rules'`)?

Might be related to already stored pushrules in the database. If you don't have configured anything special or are OK with configuring that again: Can you remove your pushrules from the database? (`DELETE FROM userapi_account_datas WHERE localpart = 'YourLocalpart' and type = 'm.push_rules'`)
After deleting you can recreate them by clearing cache in Element Web/doing an initial sync.

**Comment by Undef-a** [comment]
I did have a few, but sadly deleting them didn't fix the issue either.

**Comment by Undef-a** [comment]
Looks like the issue above is on the Fluffychat side. If you've already logged in upgrading to the new version will still fail to start even with these patches. 

Logging out of Fluffychat and back in fixes it.

**Review by kegsay — APPROVED** [review]
Need coverage up, but LGTM

**Pull request merged**
