### PR TITLE
Rewrite Startup for using cobra (and koanf)

### LINKED ISSUE #2591: Configuration by Environment Variables
**Description:**

In a K8s it is really common to run dependencies by other applications like an database operator (zalando's postgres operator). Which generates k8s secrets, for credentials like username and password.

It would be nice to use them directly (instatt of generate configfiles, stored in new k8s secrets with helm or other tooling). Therefore exists the possibility to use envFromSecrets in k8s deployments.

---

So please make it possible to give dendrite configuration parameters with env variables.

---

Maybe you like to use the golang library viper and cobra from spf13 for it.

### PR DESCRIPTION
**Pull request by genofire**
improvements are:
- one binary also for service like
  - [x] create-account
  - [x] generete-config
  - [x] generate-keys
  - [x] monolith
  - [x] polylith (with there components)
  - [x] version
- config reading with:
  - toml
  - yaml
  - json
  - env:
      - [ ] split database uri into components (e.g. for set password on another way then host - k8s secrets vs. configmaps)
      - works level of `struct` are `__` (two underscore - so e.g. `server_name` is the same on yaml): 
          - e.g. set `DENDRITE_GLOBAL__SERVER_NAME`
      - e.g for `create-account` without config-file:
       ```bash
       export DENDRITE_GLOBAL__PRIVATE_KEY="matrix_key.pem" DENDRITE_CLIENT_API__REGISTRATION_SHARED_SECRET="a"; ./dendrite create-account --username a
       ```

- config writing (by `generete-config` with env and cli-flags configurated) into yaml

fix #2591, #1958, #393.

PS: viper has some problems with parsing env and is not possible to disable file reading

---

that would be the new structure:
if you like it, i will reimplement the rest - please feedback @neilalexander 

---
### CMD Helps
```
Dendrite is a second-generation Matrix homeserver written in Go.
It intends to provide an efficient, reliable and scalable alternative to Synapse.

Usage:
  dendrite [command]

Available Commands:
  account     Manage Account on this server
  completion  Generate the autocompletion script for the specified shell
  config      Configuration tools
  help        Help about any command
  keys        key tools
  server      run the server

Flags:
  -h, --help      help for dendrite
  -v, --version   version for dendrite

Use "dendrite [command] --help" for more information about a command.
```
<details>
  <summary>account</summary>

```
Manage Account on this server

Usage:
  dendrite account [command]

Available Commands:
  create      Creates a new user account on the homeserver.

Flags:
  -h, --help   help for account

Use "dendrite account [command] --help" for more information about a command.
```
</details>
<details>
  <summary>account create</summary>

```
Creates a new user account on the homeserver.

Usage:
  dendrite account create [flags]

Flags:
      --admin                 Create an admin account
  -c, --config string         config file
  -h, --help                  help for create
      --password string       The password to associate with the account
      --passwordfile string   The file to use for the password (e.g. for automated account creation)
      --passwordstdin         Reads the password from stdin
      --reset-password        Deprecated
      --timeout duration      Timeout for the http client when connecting to the server (default 30s)
      --url string            The URL to connect to. (default "https://localhost:8448")
      --username string       The username of the account to register (specify the localpart only, e.g. 'alice' for '@alice:domain.com')
```
</details>
<details>
  <summary>config</summary>

```
Configuration tools

Usage:
  dendrite config [command]

Available Commands:
  generate    generate configuration file
  verify      verify configuration

Flags:
  -h, --help   help for config

Use "dendrite config [command] --help" for more information about a command.
```
</details>
<details>
  <summary>config generate</summary>

```
generate default configuration (overwrite is possible by commandline arguments and enviroment variables

Usage:
  dendrite config generate [flags]

Flags:
      --ci              Populate the configuration with sane defaults for use in CI
  -c, --config string   write config to file if not set to print in yaml
      --db string       The DB URI to use for all components if not SQLite files
      --dir string      The folder to use for paths (like SQLite databases, media storage) (default "./")
  -h, --help            help for generate
      --monolithic      Generate a config that makes sense for monolith deployments (default true)
      --server string   The domain name of the server if not 'localhost'
```
</details>
<details>
  <summary>config verify</summary>

```
verify configuration - read file+env and print result

Usage:
  dendrite config verify [flags]

Flags:
  -c, --config string   write config to file if not set to print in yaml
  -h, --help            help for verify
      --monolithic       (default true)
```
</details>
<details>
  <summary>keys</summary>

```
key tools

Usage:
  dendrite keys [command]

Available Commands:
  generate    Generate key files which are required by dendrite.

Flags:
  -h, --help   help for keys

Use "dendrite keys [command] --help" for more information about a command.
```
</details>
<details>
  <summary>keys generate</summary>

```
Generate key files which are required by dendrite.

Usage:
  dendrite keys generate [flags]

Flags:
  -h, --help                        help for generate
      --keysize int                 Optional: Create TLS RSA private key with the given key size (default 4096)
      --private-key string          An Ed25519 private key to generate for use for object signing
      --server string               Optional: Create TLS certificate/keys with this domain name set. Useful for integration testing.
      --tls-authority-cert string   Optional: Create TLS certificate/keys based on this CA authority. Useful for integration testing.
      --tls-authority-key string    Optional: Create TLS certificate/keys based on this CA authority. Useful for integration testing.
      --tls-cert string             An X509 certificate file to generate for use for TLS
      --tls-key string              An RSA private key file to generate for use for TLS
```
</details>
<details>
  <summary>server</summary>

```
run the server

Usage:
  dendrite server [command]

Available Commands:
  run         Run dendrite server

Flags:
  -h, --help   help for server

Use "dendrite server [command] --help" for more information about a command.
```
</details>
<details>
  <summary>server run (monolith + list commands/components for polylith)</summary>

```
Run dendrite server in monolith modus (if no component called)

Usage:
  dendrite server run [flags]
  dendrite server run [command]

Available Commands:
  appservice    Run dendrite server polylith component: appservice
  clientapi     Run dendrite server polylith component: clientapi
  federationapi Run dendrite server polylith component: federationapi
  keyserver     Run dendrite server polylith component: keyserver
  mediaapi      Run dendrite server polylith component: mediaapi
  roomserver    Run dendrite server polylith component: roomserver
  syncapi       Run dendrite server polylith component: syncapi
  userapi       Run dendrite server polylith component: userapi

Flags:
      --api                               Use HTTP APIs instead of short-circuiting (warning: exposes API endpoints!)
      --api-bind-address string           The HTTP listening port for the internal HTTP APIs (if -api is enabled) (default "localhost:18008")
  -c, --config string                     config file
  -h, --help                              help for run
      --http-bind-address string          The HTTP listening port for the server (default ":8008")
      --https-bind-address string         The HTTPS listening port for the server (default ":8448")
      --really-enable-open-registration   This allows open registration without secondary verification (reCAPTCHA). This is NOT RECOMMENDED and will SIGNIFICANTLY increase the risk that your server will be used to send spam or conduct attacks, which may result in your server being banned from rooms.
      --tls-cert string                   The PEM formatted X509 certificate to use for TLS
      --tls-key string                    The PEM private key to use for TLS

Use "dendrite server run [command] --help" for more information about a command.
```
</details>
<details>
  <summary>server run appservice (polylith component - appservice as e.g.)</summary>

```
Run dendrite server polylith component: appservice

Usage:
  dendrite server run appservice [flags]

Flags:
  -h, --help   help for appservice

Global Flags:
  -c, --config string   config file
```
</details>

### CODE REVIEW

**Comment by S7evinK** [comment]
I like the idea. How does the binary size look like with cobra?

Right now:
```
-rwxr-xr-x 1 41352928 Aug 12 21:15 bin/dendrite-monolith-server
-rwxr-xr-x 1 41064704 Aug 12 21:15 bin/dendrite-polylith-multi
```

**Comment by genofire** [comment]
current size (13MB):
```
rwxr-xr-x  1 genofire genofire 12956781 Aug 12 21:19 dendrite
```

**Comment by genofire** [comment]
testing monolith with loading yaml-file, now.
Looks good.

**Comment by genofire** [comment]
so polylith and create-account is also reimplement.

Just one think todo, improve `connection_string` for handling username and password with own env-variables.

Feedback/Review is welcome.

**Comment by ealib** [comment]
Sorry to be late to the party. I like this approach, but, personally, I would like the command line to be more subsystem-oriented with verbs explicitly aimed at that part of the application. If you like, a more ergonomic command line, more easily memorised 'by pattern', without, in the future, forcing somersaults and inconsistencies between similar commands.

The general syntax should follow these patterns:

```
dendrite [general-options]

dendrite {subsystem} [general-options]

dendrite {subsystem} {verb} [general-options] [verb-options]

```

where *general-options* are

```
-h -help --help
-v -verbose --verbose
-c -config --config
```

Let me explain with a few examples. Translating some examples by  @genofire

```
dendrite autocompletion-script generate

dendrite account create

dendrite config generate

dendrite keys generate

dendrite server run

```

This scheme would easily allow the command line to be maintained and extended congruently, throughout the product life cycle. Let us look at some possible commands that might be useful in the future:

```
dendrite account disable
dendrite account delete
dendrite account reset-password
dendrite account invite
dendrite config verify
dendrite config backup
dendrite keys verify
dendrite keys backup
dendrite server pause
dendrite server restart
dendrite room create
dendrite room purge
dendrite room sanitize
...
```

**Comment by genofire** [comment]
@ealib i have done it - where it is possible.
- autocompletion is part of cobra, i do not like and know current where to put it
- `-c -config --config` is still only `-c --config` and only on commands where the config-file is needed.

---

i like to review and merge this version/merge.
The last nice to have i would make later (to rearrange/split the database string to parts for k8s)

**Comment by spaetz** [comment]
I like the cobra change in general (can't comment on the koanf(?) one), command line handling always had felt a bit manual and fragile (but then I am used to Python's argparse, so I am biased).

**Review by kegsay — CHANGES_REQUESTED** [review]
Having something like cobra sounds reasonable - having a single binary with actions and flags is generally a more modern approach to CLI tools (see k8s, docker, awscli which all do similar).

I dislike koanf, because it adds a lot of extra complexity and flexability for extremely limited gains. My specific problems with it are:
 - Complexity. Supporting many configuration formats can cause headaches at both the technical and developer level. Technically, it means you never know which data types can be easily represented and which are more difficult e.g multi-line strings and arbitrary k-v maps are typically hard to represent as env vars. Similarly, it becomes harder to write good key names as you don't know if the format is case-insensitive or disallows certain special characters. At a developer level, we now need to be able to debug user reports done in `$insert_config_format` rather than just saying "we support YAML".
 - Flexibility. some data formats can be specified at the same time, e.g env vars with a YAML file, and it's unclear what should happen in this circumstance. At best, the result can be surprising from an end-user perspective. At worst, it can result in a security vulnerability because we let env vars control something sensitive or because we are overly flexible on which files we read from. 

Please strip out the koanf changes until we can assess the potential risks.

**Comment by genofire** [comment]
The koanf, is the main reason for this PR.
I like and need Env handling for a good and easy deployment in k8s.
- For User, the circual should be clear, default values could be overwrite by configfile. now, this could be overwrite by env. The other file formats are just a benefit, because the marshaling is so easy. (You could still document, that other files then YAML are not supported for issues - or i really drop the other fileparser)
  - but i could implement also a `config verify`, where the result config is dumped, that everyone could see, what values would be used on server run
- For developer, it does not change anything, the use the golang struct dor configuration.

**Comment by neilalexander** [comment]
For what it's worth, I'm not really comfortable with a multi-format config file either at this stage. We don't consider the configuration file to be stable in nature until we hit Dendrite 1.0 and this change will make it considerably harder for us to make changes and notify users of them.

In addition to that, there are any number of ways that having multiple configuration formats can confuse users or go wrong. It increases the support burden for us dramatically when a user comes to us with a problem, since we can no longer point them at a single canonical configuration file to use as a template. There may be subtle differences in value handling between the formats and other things we aren't aware of.

**Comment by genofire** [comment]
I rebase just to latest tag. When there are conflicts i will resolve it after all reviews are correct.

- i drop json and toml support - for only yaml
- add `dendrite config verify` command to see config which is used on running

**Comment by kegsay** [comment]
We recently updated our [contributing guidelines](https://github.com/matrix-org/dendrite/blob/main/docs/CONTRIBUTING.md#contribution-types). This PR is being closed because it isn't a feature we want to maintain going forwards. This PR notably increases the configuration API surface significantly, which is the opposite to what we want to do to ensure Dendrite remains maintainable with a small team.

**Pull request closed without merging**
