### PR TITLE
Admin endpoint documentation

### PR DESCRIPTION
**Pull request by timaeos**
### Pull Request Checklist

Adding additional documentation to the administration APIs section for 
- Server Notices
- Admin Whois

Additionally providing information on how to use curl with the administration endpoints for first time users.
No tests required due to lack of coding changes and scope limited to documentation.

* [O] I have added added tests for PR _or_ I have justified why this PR doesn't need tests.
* [O] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/main/docs/CONTRIBUTING.md#sign-off)

Signed-off-by: `Timothy Arnold <timaeos@proton.me>`

### CODE REVIEW

**Comment by timaeos** [comment]
Please let me know if there are any changes you would like me to make to this PR

**Review by S7evinK — APPROVED** [review]
Maybe add something about making your user an admin:

```
UPDATE account_accounts SET account_type = 3 WHERE localpart = '$localpart';
``` 
and how to retrieve an `access_token`, otherwise looks good!

**Comment by timaeos** [comment]
> Maybe add something about making your user an admin:
> 
> ```
> UPDATE account_accounts SET account_type = 3 WHERE localpart = '$localpart';
> ```
> 
> and how to retrieve an `access_token`, otherwise looks good!

Alright, added some brief information on how to get `access_token` from an element-base client and added a section discussing how to make an existing user an administrator

**Comment by S7evinK** [comment]
Thanks for this!

**Pull request merged**
