### PR TITLE
[WIP] Add Presence module

### PR DESCRIPTION
**Pull request by S7evinK**
WIP of a presence implementation. (#602)

Todo:
- [x] Implement `GetPresence`
- [x] Add `m.presence` to gomatrixserverlib
- [x] Implement `/sync`
- [x] Implement federationapi & sender

Questions:
- Where to store the data? (memory is not possible, as we need to store e.g. `status_msg`)
- Add a new component? (would make sense for the future, scaling wise [IMHO])

### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by r3k2** [comment]
When will this be on master?

**Comment by S7evinK** [comment]
@r3k2 There are still some missing pieces (e.g. database), which I didn't start yet.

**Comment by S7evinK** [comment]
@kegsay @neilalexander 
Opinions on where to store the data?

`syncapi` (same as receipts) - would require an `inthttp` package for getting the presence from the `clientapi`
`eduserver` - would require a new database

The other idea would be, as mentioned, a new component with the known pros/cons.

**Comment by kegsay** [comment]
Adding components is extremely costly and incurs IPC costs on any public API. We generally want to stick logic to orthogonal scaling points. Presence will scale based on the number of users independent of rooms, which is the same as the user API, so that feels like the most logical place to put this.

**Comment by r3k2** [comment]
Good work with this @S7evinK I seen in the last 2 weeks there was a lot of things added, and you stuck on the checks... any ETA on this?

**Comment by S7evinK** [comment]
Thing is, Sytest is using deprecated endpoints, so most of the [tests](https://github.com/matrix-org/dendrite/issues/602#issuecomment-679217922) listed will not pass at the moment. I've created an [issue](https://github.com/matrix-org/sytest/issues/1108) for that.

I've been running this for a week or so and only found one issue i need to fix. (unsure if the outbound federation is working correctly, but inbound looks good)

**Comment by kegsay** [comment]
If you're only stuck on the sytests, I can convert them to be using `/sync`.

**Comment by S7evinK** [comment]
I *think* the sytests are the last missing pieces. Thanks for having a look at them. :)
Tested the federation part earlier today with two dendrite monoliths, seems to work so far. Will have a look at optimizing the incoming path, as currently every presence event is directly send to the userapi, which should be better in bulk.

**Comment by r3k2** [comment]
yay! @S7evinK  thanks for your work on this. hopefully @kegsay  etc will push to master soon.

**Comment by S7evinK** [comment]
Unfortunately still stuck with the following tests. full-api mode is a bit worse, probably just error handling, didn't have a look at that yet.
```
Presence: 67% (10/15 tests)
    × Newly joined room includes presence in incremental sync
    × Get presence for newly joined members in incremental sync
    × User sees their own presence in a sync
    × User sees updates to presence from other users in the incremental sync.
    × New federated private chats get full presence information (SYN-115)
```

**Comment by thinkwelltwd** [comment]
I'm doing some due diligence research about moving to a multi-homeserver Matrix deployment. For performance benefits, I'd be very glad to deploy Dendrite, but for the lack of presence. Is there any sort of ETA (ie 1-6 months) for this PR, or should I just plan to go with Synapse?

**Comment by S7evinK** [comment]
As there have been many changes since I've started working on this, and I now know better (hopefully), I'll close this for now. But definitely will revisit this, unfortunately no ETA on this.

**Pull request closed without merging**
