### PR TITLE
ThreePid component

### PR DESCRIPTION
**Pull request by PiotrKozimor**
First step to implement #1298. 

`ThreePid` component is introduced which would handle validate session. It will have interface as defined in [api.go](https://github.com/globekeeper/dendrite/blob/piotr-kozimor/hs-sends-emails/threepid/api.go). 
Database implementation for storing sessions is defined by `storage` interface. 

### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

Signed-off-by: `Piotr Kozimor <p1996k@gmail.com>`

### CODE REVIEW

**Comment by Kegsay** [comment]
Please don't do this as a separate component. There's no need to make every feature a component. Components should be used when there is a real risk of high CPU/RAM consumption such that offloading that to another machine and/or sharding it is desirable. In this case, that is not a concern. There is a cost to adding components hence the desire to keep these as low as feasibly possible.

**Comment by PiotrKozimor** [comment]
Ok, it makes sense. I guess I will merge the defined `API` interface with `UserInternalAPI`. Do you have any comments for interface that I have already defined?

**Comment by kegsay** [comment]
Merging it with `UserInternalAPI` makes sense as it should scale with the number of users. It's hard to comment on the API when I can't see how it's being used unfortunately.

At a glance it seems plausible, just be careful not to introduce race conditions (`IsSessionValidated` followed by `ValidateSession` for example will race if a session is in the process of being validated when `IsSessionValidated` is called).

**Comment by PiotrKozimor** [comment]
I am closing this for clarity, in favour of #1970

**Pull request closed without merging**
