### PR TITLE
fix(helm): extract image tag to value (and use as default from Chart.…

### PR DESCRIPTION
**Pull request by genofire**
improve image tag handling on the default helm way.
with usage of appVersion from:
https://github.com/matrix-org/dendrite/blob/0995dc48224b90432e38fa92345cf5735bca6090/helm/dendrite/Chart.yaml#L4

maybe you like to review @S7evinK ?

### Pull Request Checklist

* [x] I have added Go unit tests or [Complement integration tests](https://github.com/matrix-org/complement) for this PR _or_ I have justified why this PR doesn't need tests
* [x] Pull request includes a [sign off below using a legally identifiable name](https://matrix-org.github.io/dendrite/development/contributing#sign-off) _or_ I have already signed off privately

Signed-off-by: `Geno <geno+dev@fireorbit.de>`

### CODE REVIEW

**Review by S7evinK — APPROVED** [review]
Other than CT expecting a new chart version, LGTM!

**Comment by genofire** [comment]
i increase the helm chart version - about an patch level.

in focus of [helm's conventions](https://helm.sh/docs/chart_best_practices/conventions/#version-numbers) of [semantic versioning](https://semver.org/) it is an breaking change (ala new value format) - so  it had to change it to an major version.

so please give me an hint, if i should change it to an major

---

by the way - why not started from scratch with the helm-chart release ....

**Comment by genofire** [comment]
@S7evinK you miss to update `appVersion` (and with this PR abolute code legacy `image.repository`) with the release of dendrite in version `0.10.9`

**Review by S7evinK — APPROVED** [review]

**Comment by S7evinK** [comment]
> @S7evinK you miss to update `appVersion` (and with this PR abolute code legacy `image.repository`) with the release of dendrite in version `0.10.9`

Oh, yea, looks like that. :/

I'm fine with the patch version, given the chart isn't really "battle tested" yet.

**Pull request merged**
