### PR TITLE
Implement event redaction

### LINKED ISSUE #620: Implement event redaction
- [ ] Implement [m.room.redaction](https://matrix.org/docs/spec/client_server/r0.4.0.html#m-room-redaction)
- [ ] Implement [PUT /_matrix/client/r0/rooms/{roomId}/redact/{eventId}/{txnId}](https://matrix.org/docs/spec/client_server/r0.4.0.html#put-matrix-client-r0-rooms-roomid-redact-eventid-txnid)

We already handle redacted event so this shouldn't be too hard.

### PR DESCRIPTION
**Pull request by Cnly**
Fixes #620.

This PR also includes a minor database fix taken from #696.

This PR doesn't provide full check on redactor's power level yet, which should be fixed at some point later, together with Dendrite's other power level TODOs. Another aspect in which it can be improved is that some similar code appearing in both roomserver and syncapi may be able to get factored out somewhere.

Signed-off-by: Alex Chen <minecnly@gmail.com>

### Pull Request Checklist

* [x] I have added any new tests that need to pass to `testfile` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by anoadragon453** [comment]
Could you merge this forward please?

**Comment by Kegsay** [comment]
Thanks for your time on this. I would be interested in merging this in, but it needs a merge forward, and SQLite support.

If you're in a position to do this, that would be great. If not, I'll likely get around to it somepoint soon. Assigning this to me to see this to its conclusion regardless.

**Comment by Kegsay** [comment]
Closing this PR for now. When we implement redaction we'll use this for inspiration!

**Comment by Kegsay** [comment]
Redaction is now implemented as of https://github.com/matrix-org/dendrite/pull/1189 - we went with a slightly different approach but all the sytests pass :D

**Pull request closed without merging**
