### PR TITLE
Reject rooms v6 invites with invalid JSON

### LINKED ISSUE #1313: Reject rooms v6 invites with invalid JSON
Sytests:
```
    × Inbound federation rejects invites which include invalid JSON for room version 6
    × Outbound federation rejects invite response which include invalid JSON for room version 6
    × Inbound federation rejects invite rejections which include invalid JSON for room version 6
```

### PR DESCRIPTION
**Pull request by S7evinK**
Unfortunately, this requires `pkg/errors`.
Otherwise we'd just be able to check for `BadJSONError`
Depends on matrix-org/gomatrixserverlib/pull/241
Closes #1313

### Pull Request Checklist

* [x] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Review by neilalexander — CHANGES_REQUESTED** [review]
I would expect to see the `go.mod`/`go.sum` file updated to point to matrix-org/gomatrixserverlib@2c145ad since that is prerequisite to some code here—from the top-level folder of the repository:
```
go get github.com/matrix-org/gomatrixserverlib@2c145ad
go mod tidy
git add go.mod go.sum
```

**Comment by S7evinK** [comment]
I just saw that this will probably not work for the http api tests. :/

**Comment by Kegsay** [comment]
What's the status on this PR?

**Comment by S7evinK** [comment]
Currently on hold, since there isn't a proper way to handle the errors on API boundaries yet. (-> blocked by https://github.com/matrix-org/dendrite/issues/1441)

**Comment by Kegsay** [comment]
This PR has been marked as stale and will be closed in 1 week if there are no further commits.

**Comment by S7evinK** [comment]
Closed, for being stale and waiting for https://github.com/matrix-org/dendrite/issues/1441.

**Pull request closed without merging**
