### PR TITLE
Switch to Go 1.19 as minimum

### PR DESCRIPTION
**Pull request by 0x1a8510f2**
## Reasoning

[Go 1.19](https://tip.golang.org/doc/go1.19) has been out for over a month now (02/08/2022) and features some changes which are likely to be quite beneficial here (see https://github.com/matrix-org/dendrite/issues/2564). Perhaps most importantly, the release allows one to set a soft memory limit on the runtime which helps a lot in the P2P usecase.

Other noteworthy changes include:
- Performance improvements (especially on RISC-V)
- Some security improvements
- More stdlib atomic types (no need for `go.uber.org/atomic` anymore)
- Automatic file descriptor limit increase on unix-like systems

Hence, I think it's worth incrementing the minimum supported version to benefit from the above.

As an alternative, I could revert backwards-incompatible changes and just use go 1.19 in CI to benefit from most of this but still allow building with 1.18. That said, I personally think the code removed because of the upgrade warrants incrementing the minimum.

No tests needed beyond what already exists as this doesn't really change the code in any meaningful way.

## Changes Summary

- Replace all usage of Go 1.18 with Go 1.19
- Use debian bullseye over debian stretch
- Remove now-obsolete file descriptor limit increase code (the commit says memory limit because it's 2am and I'm tired)
- Simplify unix build constraints
- Replace usage of `go.uber.org/atomic` with `sync/atomic` and move the former into the indirect deps section in `go.mod`
- Fix a minor typo in log

## Side Note

https://github.com/matrix-org/dendrite/blob/af9a204cc0b997bf0b7fd6ea434a7c04157bdf28/syncapi/storage/postgres/filtering.go#L41-L50

I came across this comment while searching for `1.18`. I assume the comment means the function should be merged with the duplicate below it using generics? Unfortunately, Go generics don't allow for accessing properties, only methods. Should I remove the comment?

## Pull Request Checklist

* [x] I have added added tests for PR _or_ I have justified why this PR doesn't need tests.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/main/docs/CONTRIBUTING.md#sign-off)

Signed-off-by: `0x1a8510f2 <admin@0x1a8510f2.space>`

### CODE REVIEW

**Comment by 0x1a8510f2** [comment]
My git-fu failed me. Gonna re-open

**Comment by bones-was-here** [comment]
Debian stable backports doesn't have 1.19 yet.

**Comment by 0x1a8510f2** [comment]
@bones-was-here do you mean, as a reason not to upgrade to 1.19 yet or are you referring to the commit where I switch to using bullseye for building? If the latter, I'm using the container (https://hub.docker.com/_/golang) which does have 1.19.

**Comment by bones-was-here** [comment]
dendrite 0.9.8 builds and works on go 1.18, which is in backports

**Pull request closed without merging**
