### PR TITLE
Automate release binaries

### PR DESCRIPTION
**Pull request by acheong08**
Automatically upload build artifacts and attach to release.

Signed-off-by: `Antonio Cheong <acheong@student.dalat.org>`

### CODE REVIEW

**Comment by acheong08** [comment]
Example release: https://github.com/acheong08/dendrite/releases/tag/v0.12.2

**Comment by acheong08** [comment]
Looks like pull bot force pushed and deleted the merge request then got it merged?

**Comment by S7evinK** [comment]
We're as confused as you, as this got automatically merged when I merged https://github.com/matrix-org/dendrite/pull/3187

**Comment by acheong08** [comment]
The fact that this was automatic should be a security concern

**Comment by acheong08** [comment]
I successfully replicated this issue:
- https://github.com/acheong08/merge-issue-example/pull/7

It happens when the branch is force pushed to a commit hash that has yet to be commited. It will automatically be merged if the commit is pushed.

**Pull request merged**
