### PR TITLE
fix(helm): do not deploy screenshot to cluster (just dashboard)

### PR DESCRIPTION
**Pull request by genofire**
### Pull Request Checklist

* [x] I have added Go unit tests or [Complement integration tests](https://github.com/matrix-org/complement) for this PR _or_ I have justified why this PR doesn't need tests
* [x] Pull request includes a [sign off below using a legally identifiable name](https://matrix-org.github.io/dendrite/development/contributing#sign-off) _or_ I have already signed off privately

Signed-off-by: `Your Name <your@email.example.org>`

### CODE REVIEW

**Review by kegsay — APPROVED** [review]

**Comment by kegsay** [comment]
Needs a version bump though.

**Comment by genofire** [comment]
And DOC, i know ... will make later.

**Comment by genofire** [comment]
ready to merge ;)

**Comment by genofire** [comment]
PS: What is wrong with the current dendrite? (v0.12.0 has an broken healthy-check)

**Pull request merged**
