### PR TITLE
Add AS support to common.MakeAuthAPI

### PR DESCRIPTION
**Pull request by APwhitehat**
* Integrate #433 into `common.MakeAuthAPI`
* Update `clientapi.routing` to utilize the AS support.
* Make other Components work ok with the new `common.MakeAuthAPI`, Add "TODO" to help their migration.

### CODE REVIEW

**Comment by erikjohnston** [comment]
Couple of comments:

1. We probably want to refactor `MakeAuthAPI`, its got too many parameters as it is and its confusing
2. I wonder if we should make an `authtypes.Device` for AS users?

**Comment by APwhitehat** [comment]
1. I agree.
2. I thought AS users do not have a device. Did you mean a dummy device with AS service's AccessToken & userID ?

**Comment by APwhitehat** [comment]
Once matrix-org/gomatrixserverlib#92 gets merged, we can remove the "AS_Device" with a const.

**Comment by anoadragon453** [comment]
API endpoints such as this one:
https://github.com/matrix-org/dendrite/blob/78440083dfc8f522e55f11f0fce0f3ea4a103f0b/src/github.com/matrix-org/dendrite/clientapi/routing/createroom.go#L160

still check for information from the accountDB, which fails due to an account not actually existing.

What do you think of the solution of just creating a `sender_localpart` account on startup for each appservice if it doesn't already exist?

**Pull request merged**
