### PR TITLE
Fix `/login` issue causing wrong device list updates

### PR DESCRIPTION
**Pull request by S7evinK**
Fixes https://github.com/matrix-org/dendrite/issues/2914 and possibly https://github.com/matrix-org/dendrite/issues/2073?

### CODE REVIEW

**Review by kegsay — CHANGES_REQUESTED** [review]
Make `PasswordRequest.Username()` return the lower-cased correct username by default please. Then add something like `.RawUsername()` for matching when there is no matching user.

**Comment by S7evinK** [comment]
> Make `PasswordRequest.Username()` return the lower-cased correct username by default please. Then add something like `.RawUsername()` for matching when there is no matching user.

I'm currently not seeing the benefit of that. With that we'd need to actually take care of those cases where we use `.Username()` right now. e.g. when deactivating an account, we would have to try both cases (raw and lower-cased) instead of setting it correctly once on login.

**Comment by kegsay** [comment]
The benefit is that you don't need to set the field (or forget to set the field..), and it makes it clear what is processed/validated input vs untrusted/potentially invalid input. When verifying the account exists, we are forced unfortunately to check both, but then once this check has been done then code which just wants to know the username can just call `.Username()`?

**Review by kegsay — APPROVED** [review]
After talking it through, LGTM

**Pull request merged**
