### PR TITLE
Move to go mods instead of gb (#700)

### LINKED ISSUE #700: Move to go mods instead of gb
Go mods is the modern and officially supported method for vendor package versioning and building outside GOPATH. For VS Code with the golang extension devs, gb does not seem to integrate with the tools used by the extension, severely limiting the IDE capabilities of VS Code (code completion, lookup, etc). Additionally, the official site for [gb](getgb.io) seems to be offline due to domain registration issues. For these reasons, I think it's worthwhile to change the vendor management strategy to go mods.

As a new contributor to the project, this is an issue I'd like to take up if there is agreement on moving forward.

### PR DESCRIPTION
**Pull request by frzifus**
close #700 

1. removed all gb related stuff

2. init go mod & update vendor

3. the minimum golang version has been raised to `1.11`. Because only with this version go modules are supported.

4. documentation has been adapted

5. removed `golint` from linters. as already stated in https://github.com/matrix-org/dendrite/issues/697 `gometalinter` is obsolete. This leads to problems in ci because [this pkg](github.com/golang/lint/golint) is not reachable. i removed it. [See](https://github.com/alecthomas/gometalinter/blob/master/linters.go#L290)

6. after the vendor update, `go vet` messed up the build. fixed it. 
```bash
# github.com/matrix-org/dendrite/cmd/create-room-events
create-room-events/main.go:142:9: Errorf format %q has arg format of wrong type *string
```

Signed-off-by: Benedikt Bongartz <benne@klimlive.de>

### CODE REVIEW

**Comment by frzifus** [comment]
although `golint` was removed, this error still occurs. [See](https://travis-ci.org/matrix-org/dendrite/jobs/534067249)
```golang
gometalinter: error: failed to install the following linters: github.com/golang/lint/golint
The command "./scripts/travis-test.sh" exited with 1.
```

That just occurred when while starting the integration test. [See](https://travis-ci.org/matrix-org/dendrite/jobs/534067251)
```bash
--2019-05-18 02:24:25--  http://apache.mirror.anlx.net/kafka/2.1.0/kafka_2.11-2.1.0.tgz
Resolving apache.mirror.anlx.net (apache.mirror.anlx.net)... 81.91.108.244
Connecting to apache.mirror.anlx.net (apache.mirror.anlx.net)|81.91.108.244|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-05-18 02:24:26 ERROR 404: Not Found.
```

how could that ever have worked? :lollipop:

**Comment by Cnly** [comment]
I think this has been achieved by #594?

**Comment by frzifus** [comment]
nice good job :+1:

**Comment by babolivier** [comment]
Oh yeah, I forgot to post a comment here last night. Sorry we obsoleted your PR, thank you very much for your work anyway @frzifus! :+1:

**Pull request closed without merging**
