### PR TITLE
check for nil body prior to unmarshal

### PR DESCRIPTION
**Pull request by yozamacs**
### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `testfile` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/CONTRIBUTING.md#sign-off)

This is a redo of https://github.com/matrix-org/dendrite/pull/790 regarding issue https://github.com/matrix-org/dendrite/issues/767.

I'm not entirely certain that checking that the body is nil in this way will work. According to the go documentation in [request.go](https://golang.org/src/net/http/request.go) it says that 
```
	// For client requests, a nil body means the request has no
	// body, such as a GET request. The HTTP Client's Transport
	// is responsible for calling the Close method.
```
which seems like the use case that the issue is referring to. 

I haven't added any tests yet, I would like some guidance on how tests work for this project.

### CODE REVIEW

**Comment by yozamacs** [comment]
I don't understand this error, `clientapi/routing/membership.go:48: File is not `goimports`-ed (goimports)`. I ran `goimports -e -d` manually and didn't get any output. I see the same error when I run `./scripts/build-test-lint.sh` locally but not sure how to address

**Comment by Cnly** [comment]
From my reading I think `Body` will always be non-`nil` since we're on the server side:

```go
	// For server requests, the Request Body is always non-nil
	// but will return EOF immediately when no body is present.
	// The Server will close the request body. The ServeHTTP
	// Handler does not need to.
	Body io.ReadCloser
```

A better way to do this may be to check `ContentLength`.

And "File is not `goimports`-ed" means you haven't formatted the file with `goimports`; you need to run `goimports -w clientapi/routing/membership.go` ("-ed" is the past particle here, not flags to use). You may also run `goimports -h` to see the help text. Basically if you're using an IDE, it may already have integrated the tool and it shouldn't be hard to let your IDE do this automatically.

**Comment by Kegsay** [comment]
Missing sign-off and this could really do with a sytest (POSTing to /leave with an empty body).

**Comment by Kegsay** [comment]
https://github.com/matrix-org/dendrite/pull/839 is a better fix for this.

**Pull request closed without merging**
