### PR TITLE
Fixing Presence Conflicts

### PR DESCRIPTION
**Pull request by jjj333-p**
This is meant to cache client presence for a moment so that it doesn't oscillate. 

Currently Dendrite just federates out whatever presence it gets from the sync loop, which means if theres any clients attempting to sync without setting the user online, and there is an online client, it will just flip back and forth each time one of the clients polls /sync. 

This pull request essentially stores in a map when the client last set online ideally to allow the online client to sync again and set an online presence before setting idle or offline.

I am not great at programming nor am I familiar with this codebase so if this pr is just shitwater feel free to discard, just trying to fix an issue that severely bothers me. If it is easier you can also steal the code and write it in yourself. I ran the linter, not sure that it did anything, the vscode go extension seems to format and lint anyways. 

I tried to run unit tests but I have no idea any of this thing. it errors on `TestRequestPool_updatePresence/same_presence_is_not_published_dummy2 (10m0s)` which I think making this change broke. I am unsure how to comply, if y'all point me in the right direction ill try to fix it. I have tested it with all the situations I can think of on my personal instance pain.agency, and this seems to stand up under all the previously bugged situations. 

~~My go also decided to update a bunch of the dependencies, I hate git and github and have no idea how to fix that, it was not intentional.~~ i just overwrote them with the ones from the main repo and committed it, seems to have done what was needed.

### Pull Request Checklist

* [x] I have added Go unit tests or [Complement integration tests](https://github.com/matrix-org/complement) for this PR _or_ I have justified why this PR doesn't need tests
* [x] Pull request includes a [sign off below using a legally identifiable name](https://matrix-org.github.io/dendrite/development/contributing#sign-off) _or_ I have already signed off privately

Signed-off-by: `Joseph Winkie <jjj333.p.1325@gmail.com>`

### CODE REVIEW

**Comment by jjj333-p** [comment]
Oh I should also mention don't look too closely at the commit history, this one is a squash and merge (**if it gets merged**)

**Comment by jjj333-p** [comment]
im fixing it, dont review yet I guess

**Comment by jjj333-p** [comment]
eh im in over my head and not in a mental state where it makes sense to work on this. bit of a waste of a day but :shrug: i got out of bed

**Comment by jjj333-p** [comment]
I've hopefully fixed any potential race conditions, thanks DiamondBurned for the assistance

**Comment by jjj333-p** [comment]
I could be seeing things, but this seems to have made presence with maunium bridges work correctly.

**Comment by jjj333-p** [comment]
one interesting limitation ive discovered is this means presence set through sync doesnt override explicitly set presence through the api.

the only time this matters is for some reason element ios explicitly sets presence to offline when you swipe out of the app to the homescreen. im marking this down as a client bug more than anything because why the hell would it do that

**Comment by pcouy** [comment]
I'm not a Dendrite user myself, but I'm very interested in seeing some progress on this, as my homeserver is getting presence spam from a few Dendrite instances from time to time.

I did not review your code (I don't usually write or even read go), but thank you for trying and keeping this up to date with the main branch. Have you been running this since February ? Is it going well ?

If a maintainer reads this : how can I help with making this move forward ?

PS : Disabling presence on my side does not seem to prevent receiving a deluge of presence updates.

**Comment by jjj333-p** [comment]
Yes I have been running this patch since I made it, and till has recently
for a couple weeks been running it too. I’m not sure what we can do to move
it forward.

**Comment by qwqtoday** [comment]
This sounds useful for me, hopefully the maintainers can spend some of their time on reviewing this soon

**Comment by S7evinK** [comment]
I'm basically happy with it, I just want CI to be green before merging, this needs a few other PRs to be merged before.

**Review by S7evinK — APPROVED** [review]
https://github.com/matrix-org/dendrite/pull/3397 is going to fix the media tests, so approving this one.
Thanks a lot! And sorry for the delay.

**Pull request merged**
