### PR TITLE
Only fetch events once for all rooms

### PR DESCRIPTION
**Pull request by recht**
This refactors `PDUStreamProvider` a bit so that it doesn't trigger a database query per room, but instead utilizes the fact that it's possible to bulk query. This improves sync performance significantly when you have 1000s of rooms.

### Pull Request Checklist

* [x] I have added Go unit tests or [Complement integration tests](https://github.com/matrix-org/complement) for this PR _or_ I have justified why this PR doesn't need tests
* [x] Pull request includes a [sign off below using a legally identifiable name](https://matrix-org.github.io/dendrite/development/contributing#sign-off) _or_ I have already signed off privately

Signed-off-by: `Joakim Recht <joakim@beyondwork.ai>`

### CODE REVIEW

**Comment by S7evinK** [comment]
I _think_ I tried something similar, but that made Sytest unhappy with regards to newly joined rooms on incremental syncs.

**Comment by recht** [comment]
> I _think_ I tried something similar, but that made Sytest unhappy with regards to newly joined rooms on incremental syncs.

Hmm yes I see - I have changed it a bit so that it handles the newly joined case too, and that seems to make tests run locally at least.

**Comment by recht** [comment]
I see a build is still failing, but I'm not sure the failure is related to my change?

**Review by S7evinK — APPROVED** [review]
LGTM! Thank you!
I'd like to test this on my server for a bit before merging, but my server is down as of today.. (disc I/O issues, as it seems :/)

**Comment by S7evinK** [comment]
Right, so regarding speed, it doesn't seem to change that much (well, at least for my few rooms). Most of the time is spent in `GetStateDeltas` (when setting the PDU token to `current - 100k`), but that may be something for a different PR.

**Comment by recht** [comment]
I expect for a few rooms it doesn't make any noticeable difference, but if you have many (1000s) it's very significant

**Comment by S7evinK** [comment]
Thank you for this! :)

**Pull request merged**
