### PR TITLE
Remove polylith/API mode

### PR DESCRIPTION
**Pull request by S7evinK**
This removes most of the code used for polylith/API mode.

This removes the `/api` internal endpoints entirely. 

Binary size change roughly 5%: 
```
51437560 Feb 13 10:15 dendrite-monolith-server # old
48759008 Feb 13 10:15 dendrite-monolith-server # new
```

### CODE REVIEW

**Review by kegsay — APPROVED** [review]

**Comment by genofire** [comment]
why polylith is dead now?

**Comment by mibmo** [comment]
I have similar concerns to @genofire. Is there a plan?

**Comment by S7evinK** [comment]
@genofire @mibmo - see https://github.com/matrix-org/dendrite/issues/2975#issuecomment-1435163844

**Comment by mibmo** [comment]
> @genofire @mibmo - see [#2975 (comment)](https://github.com/matrix-org/dendrite/issues/2975#issuecomment-1435163844)

Fair enough! And thanks for the link. To be honest, this seems like a better approach; Polylith was a pain anyway, though it was fun to deploy! :)
I'm excited to see how dendrite will develop.

**Pull request merged**
