### PR TITLE
Add support for server query param in publicrooms

### PR DESCRIPTION
**Pull request by prateek2211**
Signed-off-by: Prateek Sachan psachan@cs.iitr.ac.in

Fixes  part1 #638 

### Pull Request Checklist

* [X] I have added any new tests that need to pass to `testfile` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [X] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/CONTRIBUTING.md#sign-off)

### CODE REVIEW

**Comment by prateek2211** [comment]
@Kegsay I'm not able to figure out why the test `Can get remote public room list` is failing.
I have tried to pass server param on local machine, everything seems to work fine there.

Need a bit of help here.

**Comment by Kegsay** [comment]
12 bytes seems a bit small for a response with a room.
```
time="2020-04-01T17:57:19.090099173Z" level=info msg="Incoming request" func=github.com/matrix-org/util.RequestWithLogging file="/gopath/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:122" req.id=fxwNkV64MToL req.method=GET req.path=/_matrix/client/r0/publicRooms
time="2020-04-01T17:57:19.090597907Z" level=info msg="Outgoing request" func="github.com/matrix-org/gomatrixserverlib.(*Client).DoHTTPRequest" file="/gopath/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200327155501-33fb4c7049dc/client.go:379" out.req.ID=FVCO0QWHKTxD out.req.method=GET out.req.uri="matrix://localhost:8800/_matrix/federation/v1/publicRooms?include_all_networks=false&limit=0&since=&third_party_instance_id=" req.id=fxwNkV64MToL req.method=GET req.path=/_matrix/client/r0/publicRooms
time="2020-04-01T17:57:19.110408428Z" level=info msg="Outgoing request returned" func="github.com/matrix-org/gomatrixserverlib.(*Client).DoHTTPRequest" file="/gopath/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200327155501-33fb4c7049dc/client.go:393" out.req.ID=FVCO0QWHKTxD out.req.code=200 out.req.duration_ms=19 out.req.method=GET out.req.uri="matrix://localhost:8800/_matrix/federation/v1/publicRooms?include_all_networks=false&limit=0&since=&third_party_instance_id=" req.id=fxwNkV64MToL req.method=GET req.path=/_matrix/client/r0/publicRooms
time="2020-04-01T17:57:19.110618280Z" level=info msg="Responding (12 bytes)" func=github.com/matrix-org/util.respond file="/gopath/pkg/mod/github.com/matrix-org/util@v0.0.0-20190711121626-527ce5ddefc7/json.go:170" code=200 req.id=fxwNkV64MToL req.method=GET req.path=/_matrix/client/r0/publicRooms
```

So it seems like the remote queried server isn't returning the rooms.

**Comment by Kegsay** [comment]
The test tries to make a published room by performing:
```
matrix_create_room( $local_user,
         visibility      => "public",
         name            => "Test Name",
         topic           => "Test Topic",
      )
```

So I imagine `visibility: public` is not setting the published flag because it isn't implemented in Dendrite yet. https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-createroom

**Comment by prateek2211** [comment]
Oh, I get it. I manually edited the visibility column in table while testing
so, createRoom is currently ignoring the `visibility` field in the request.
I would like to add visibility check in public room creation.
Is there a corresponding issue

**Comment by Cnly** [comment]
Took a quick look and it's probably #603.

**Comment by neilalexander** [comment]
The public rooms API has been replaced as of #1174, #1176.

**Pull request closed without merging**
