### PR TITLE
Use "[]byte" instead of "json.RawMessage" if posible

### PR DESCRIPTION
**Pull request by 6543**
one step towards #1467, can not remove it completely, since gomatrixserverlib struts use it too ...

### CODE REVIEW

**Review by neilalexander — COMMENTED** [review]
I don't understand why you would want to do this?

`json.RawMessage` is a special type that the `json` library specifically uses to defer unmarshalling until a later time, which we do deliberately for a number of reasons. 

It is just a type alias of `[]byte` anyway, so you can still slice it if needed.

**Comment by 6543** [comment]
https://github.com/matrix-org/gomatrixserverlib/pull/260#issuecomment-858612394

**Comment by kegsay** [comment]
Sorry, but we don't want to do this. We can still move to jsoniter without doing this AFAIK.

**Comment by 6543** [comment]
nothing against it ... sure - will come up with a huger diff wo use *renamed imports* to introduce **jsoniter** and one with **go-json** so we can compare compatibility & speed

**Pull request closed without merging**
