### PR TITLE
Add scripts to run sytest on jenkins

### PR DESCRIPTION
**Pull request by richvdh**
The jenkins config is:

```
export BIND_HOST=127.84.48.20
export POSTGRES_DB_1=sytest_dendrite_postgres_1
export POSTGRES_DB_2=sytest_dendrite_postgres_2
./jenkins/test-monolith.sh
```

### CODE REVIEW

**Comment by ptman** [comment]
Have you tried linting using [shellcheck](https://www.shellcheck.net/) ?

**Comment by richvdh** [comment]
ptman: I have not

**Comment by ptman** [comment]
I took a look using shellcheck. Didn't find anything problematic.

**Comment by richvdh** [comment]
Thanks both

**Pull request merged**
