### PR TITLE
Switch to golangci-lint

### PR DESCRIPTION
**Pull request by anoadragon453**
As gometalinter has been discontinued, I thought it best to switch to the next popular linter, which boasts speed gains of up to 5-7x. It also includes a few more linters if we ever want to enable them.

This PR switches travis to the new linter, adds a new `./scripts/find-lint-ci.sh` script specifically for CI, whereas the user can continue to use `./scripts/find-lint.sh`. A few linting issues were also fixed to ensure the build doesn't fail.

### CODE REVIEW

**Comment by krombel** [comment]
You need to remove this folder(s) in vendor as well

**Comment by anoadragon453** [comment]
@krombel Good point, thanks!

**Comment by erikjohnston** [comment]
> As gometalinter has been discontinued

Where has that been announced? There is still activity on the GH rep

**Comment by anoadragon453** [comment]
Oh, so there is. I heard it had been discontinued a while ago on hackernews, however looking now it seems activity has picked up again in the last month.

This linter is still much faster though, so I'd still recommend it for that reason.

**Comment by APwhitehat** [comment]
I notice that safesql is absent.
Are linter.json & linter-fast.json still being used ?

**Comment by anoadragon453** [comment]
No they aren't, good point. For fast minting you can just add `--fast` to golangci-lint. I should probably add that to CONTRIBUTING and any docs that already mention linting.

**Comment by Cnly** [comment]
@anoadragon453 Is this already handled in #713?

**Comment by anoadragon453** [comment]
Indeed :) Forgot about this PR completely. Thanks for the reminder!

**Pull request closed without merging**
