### PR TITLE
Password changes

### PR DESCRIPTION
**Pull request by neilalexander**
This PR adds support for users being able to change their own password.

### CODE REVIEW

**Review by Kegsay — APPROVED** [review]
Closes https://github.com/matrix-org/dendrite/issues/407

**Comment by Kegsay** [comment]
But `    × After changing password, a different session no longer works by default` doesn't pass?

**Comment by neilalexander** [comment]
I don't really understand that `After changing password, a different session no longer works by default` test.

The test doesn't specify `logout_devices: true` so why would other access tokens be invalidated? The spec says:

> The homeserver SHOULD NOT revoke the access token provided in the request. Whether other access tokens for the user are revoked depends on the request parameters.

Must be a Synapse-ism.

**Comment by neilalexander** [comment]
Synapse appears to default to `true` for the `logout_devices` field if it isn't specified. Dendrite doesn't.

**Comment by Kegsay** [comment]
Which is correct?

**Comment by neilalexander** [comment]
Looks like the spec does say about this after all:

> Whether the user's other access tokens, and their associated devices, should be revoked if the request succeeds. Defaults to true.

I've fixed Dendrite to default to `true` also.

**Pull request merged**
