### PR TITLE
End-to-end encryption clean up and feature completion.

### PR DESCRIPTION
**Pull request by SUMUKHA-PK**
### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `testfile` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/CONTRIBUTING.md#sign-off)

Signed off by Sumukha PK (sumukhapk46@gmail.com)

PR is still a WIP, opened so that I can easiily track it and get it easily reviewed as well.

PR includes :
* The outstanding implementation of E2EE (#530 )
* Merge forward of the outstanding PR
* Checks for the existing implementation.
* Moving/writing relevant pieces of codes to/in `federationapi`
* Adding one API (`changesInKeys`) to finish the suite of E2EE

There will be a PR to `gomatrixserverlib` before this PR is merged so that the federation part of this stays there.

### CODE REVIEW

**Comment by APwhitehat** [comment]
Hey @SUMUKHA-PK 
DISCLAIMER: I am not a core Dendrite member.
Generally reviewing 1000+ lines of change is too big of a task. And I would recommend breaking this off in smaller pieces for easy reviews.
During GSoC, I was asked to do the same. :P  
Good wishes.

**Comment by SUMUKHA-PK** [comment]
Hey @APwhitehat , any suggestions?

**Comment by APwhitehat** [comment]
> Hey @APwhitehat , any suggestions?

As I said, you should try breaking this PR into 200-500 lines chunks.
Implement it in incremental changes.

Since this PR includes work of other contributors, I am not sure how feasible this advice will be.

**Comment by SUMUKHA-PK** [comment]
I am getting back to it now and then, but I wish to complete it in some time.

Yes, I know there are some huge issues in the PR. Should I break it into smaller components?

**Comment by neilalexander** [comment]
I think that would be a good idea — it might be better to submit in layers, e.g. the first being the storage layer, the second being the nice wrapper functions for it, the third being the `clientapi` integration and the fourth being the `federationapi`/`federationsender` integration. It makes it much easier for us to review in chunks and to catch any architectural decisions that might cause problems later :-)

**Comment by SUMUKHA-PK** [comment]
Sounds good. Ill hit yall up on Riot in a while. Have my mid-terms going on :)

**Comment by Kegsay** [comment]
Given the consensus is to refactor this into more manageable PRs, I'm closing this for now.

**Pull request closed without merging**
