### PR TITLE
WIP: MSC2716: Incremental existing history

### PR DESCRIPTION
**Pull request by MadLittleMods**
MSC2716: Incremental existing history

Implements https://github.com/matrix-org/matrix-doc/pull/2716 (https://github.com/matrix-org/matrix-doc/blob/matthew/msc2716/proposals/2716-importing-history-into-existing-rooms.md)

### Dev notes

Internal doc about getting started developing on dendrite: https://docs.google.com/document/d/14USwq1faRk7I2m_LacBUipFGF0-hdrglmiFpiNeGM5o/edit

 - `/_matrix/client/r0/rooms/{roomId}/send/{eventType}/{txnId}` -> [`clientapi/routing/routing.go#L213`](https://github.com/matrix-org/dendrite/blob/e1ace7e44a20be00a6db8905e5923094a37dd2ac/clientapi/routing/routing.go#L213)
  - [`clientapi/routing/sendevent.go#L45`](https://github.com/matrix-org/dendrite/blob/e1ace7e44a20be00a6db8905e5923094a37dd2ac/clientapi/routing/sendevent.go#L45)
 - `prev_event`, `PrevEventID`

---

```
./build.sh && sudo ./bin/dendrite-monolith-server --tls-cert server.crt --tls-key server.key --config dendrite.yaml -http-bind-address :8009
```

---

 - https://adoring-einstein-5ea514.netlify.app/client-server/#put_matrixclientr0roomsroomidsendeventtypetxnid

### Pull Request Checklist

* [ ] I have added any new tests that need to pass to `sytest-whitelist` as specified in [docs/sytest.md](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md)
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/dendrite/blob/master/docs/CONTRIBUTING.md#sign-off)

Signed-off-by: `Your Name <your@email.example.org>`

### CODE REVIEW

**Comment by MadLittleMods** [comment]
Closing in favor of the Synapse implementation: https://github.com/matrix-org/synapse/pull/9247

**Comment by provokateurin** [comment]
Because this was closed, does it mean dendrite has no support for backfilling as described in MSC2716? I can't find any info about that in the repo, but I'd like to use dendrite in a usecase where backfilling history is required.

**Comment by provokateurin** [comment]
Oh that's sad :( I'd really like to use dendrite for this, so I hope it is implemented once I actually get around to work on that project.

**Comment by traktuner** [comment]
+1 for this. Looking forward to [MSC2716](https://github.com/matrix-org/matrix-spec-proposals/pull/2716) - is there a timeline when this might be implemented?
Thank you!

**Pull request closed without merging**
