### PR TITLE
Use userutil to parse localpart

### PR DESCRIPTION
**Pull request by APwhitehat**
Replace SplitID with userutil wherever it's more apt.

### CODE REVIEW

**Comment by anoadragon453** [comment]
So ParseUsernameParam just uses SplitID internally, so this seems to just add more overhead. Surely we should just remove ParseUsernameParam, unless it has better error reporting?

**Comment by APwhitehat** [comment]
ParseUsernameParam handles cases where argument is just the localpart.
Also it looks kind of clearer to me :P.
Overhead should be small enough to not be noticeable.

**Comment by anoadragon453** [comment]
> ParseUsernameParam handles cases where argument is just the localpart.

Wait but then why even run the method, you already have the localpart? :P 

> Overhead should be small enough to not be noticeable.

Yeah, I do think we should try to use gomatrixserverlib functions wherever possible. Maybe we should move `ParseUsernameParam` to it ¯\\\_(ツ)\_/¯

**Comment by APwhitehat** [comment]
> Wait but then why even run the method, you already have the localpart? :P

Sometimes we don't know if client has sent localpart or the full userID, hence it becomes problematic.
eg.
https://github.com/matrix-org/dendrite/blob/a76e31f1b3ff7035b53e755c07058ff8c5f91177/src/github.com/matrix-org/dendrite/clientapi/routing/login.go#L85

> Yeah, I do think we should try to use gomatrixserverlib functions wherever possible. Maybe we should move ParseUsernameParam to it ¯\_(ツ)_/¯

definitely

**Comment by anoadragon453** [comment]
Under login on the C-S spec:

> The fully qualified user ID or just local part of the user ID, to log in.

So yes you're right, we should account for both. Still +1 for adding pretty much all userutil methods to gomatrixserverlib.

**Comment by erikjohnston** [comment]
I'd be a bit cautious about not checking that something is a valid userID in all these cases, some of the APIs the spec requires fully qualified IDs for. While it may be safe to make this change, I'm not sure if we want dendrite to be so lax compared with the spec.

**Comment by APwhitehat** [comment]
It's only safe to assume user id can be just the localpart for /login.
We may be better off having stricter checks albeit a bit ugly.

**Pull request closed without merging**
